### ISSUE TITLE
Email on https://financl.com/ doesn't work

### ISSUE THREAD

**Issue by larskarbo** [Tobeyyyyy/MacroFinance#1]
Hey!

Just tried to contact you through the contact email i found on https://financl.com/, and my email client rejected it.

Wanted to let you know!

**Comment by Tobias-Scholz** [comment]
Hi Lars,

The E-Mail was not configured correctly before. We fixed the problem. Feel free to write an E-Mail to contact@financl.com for any questions you have.

Best regards
Tobias
